server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: mini-cloud
    static_configs:
      - targets:
          - localhost
        labels:
          job: mini-cloud
          component: cloud-plane
          __path__: /var/log/mini-cloud/cloud-plane.log
      - targets:
          - localhost
        labels:
          job: mini-cloud
          component: agent
          __path__: /var/log/mini-cloud/sim-worker-*.log
